import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { useEffect, useState } from 'react'

const PokemonCard = ({ pokemon }) => {
  return (
    <>
      <div className={styles.card}>
        <div>{pokemon?.species?.name ?? 'Pokemon'}</div>
        <div>
          <img src={pokemon?.sprites?.front_default} />
        </div>
      </div>
    </>
  )
}

export default function Home() {
  const [search, setSearch] = useState('')
  const [pokemon, setPokemon] = useState({})
  const [pokemonTeam, setPokemonTeam] = useState([])

  const fetchPokemon = async () => {
    const data = await fetch(
      `https://pokeapi.co/api/v2/pokemon/${search.toLowerCase()}`
    )
    const json = await data.json()
    setPokemon(json)
  }

  const fetchRandomPokemon = async () => {
    const pokemonNumber = Math.floor(Math.random() * 909)
    const data = await fetch(
      `https://pokeapi.co/api/v2/pokemon/${pokemonNumber}`
    )
    return await data.json()
  }

  useEffect(() => {
    fetchPokemon().catch(console.error)
  }, [search])

  const handleClick = async () => {
    const pokemon = await fetchRandomPokemon()
    setPokemonTeam((team) => [...team, pokemon])
  }

  const handleClearClick = () => {
    setPokemonTeam([])
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>PokeDeck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>PokeDeck</h1>
        <input
          value={search}
          name="searchInput"
          placeholder="Enter a pokemon's name"
          onChange={(e) => setSearch(e.target.value)}
        />
        <PokemonCard pokemon={pokemon} />

        <div>
          <button onClick={handleClick}>Generate Pokemon</button>
          <button onClick={handleClearClick}>Clear</button>
        </div>

        <div className={styles.grid}>
          {pokemonTeam.map((pokemon) => {
            return <PokemonCard key={pokemon.species.name} pokemon={pokemon} />
          })}
        </div>
      </main>
    </div>
  )
}
